### ISSUE TITLE
Compiling my own version

### ISSUE THREAD

**Issue by JordanEJ** [Powerbyte7/HIDeous#1]
Hey there,

I love this project but I am wanting to tweak it to suit me a bit better. What program/script do you sure to compile it?

**Comment by Powerbyte7** [comment]
You'll need to install and use the CE toolchain to compile it, you can read about it [here](https://ce-programming.github.io/toolchain/static/getting-started.html#building-programs). It should be fairly straightfoward.

I'll add some info about the full process to the README too, because the keymap won't fit everyone and should be easy to tweak. 

I hope that helps!

**Comment by Powerbyte7** [comment]
I've documented the process with 8af3278df3e1ce45502ee612d4683f9d35759cf3, closing the issue.
